// automatically generated by the FlatBuffers compiler, do not modify

package indismqgo

const (
	ActionACK         = 0
	ActionGET         = 1
	ActionHEAD        = 2
	ActionPOST        = 3
	ActionPUT         = 4
	ActionDELETE      = 5
	ActionCONNECT     = 6
	ActionOPTIONS     = 7
	ActionTRACE       = 8
	ActionPATCH       = 9
	ActionRESPONSE    = 10
	ActionSUBSCRIBE   = 11
	ActionUNSUBSCRIBE = 12
	ActionCAST        = 13
)

var EnumNamesAction = map[int]string{
	ActionACK:         "ACK",
	ActionGET:         "GET",
	ActionHEAD:        "HEAD",
	ActionPOST:        "POST",
	ActionPUT:         "PUT",
	ActionDELETE:      "DELETE",
	ActionCONNECT:     "CONNECT",
	ActionOPTIONS:     "OPTIONS",
	ActionTRACE:       "TRACE",
	ActionPATCH:       "PATCH",
	ActionRESPONSE:    "RESPONSE",
	ActionSUBSCRIBE:   "SUBSCRIBE",
	ActionUNSUBSCRIBE: "UNSUBSCRIBE",
	ActionCAST:        "CAST",
}
