// automatically generated by the FlatBuffers compiler, do not modify

package indismqgo

const (
	ActionACK         = 0
	ActionGET         = 1
	ActionRESPONSE    = 2
	ActionSET         = 3
	ActionNEW         = 4
	ActionAPPEND      = 5
	ActionREPLACE     = 6
	ActionUPDATE      = 7
	ActionDELETE      = 8
	ActionCAST        = 9
	ActionSUBSCRIBE   = 10
	ActionUNSUBSCRIBE = 11
	ActionCONNECT     = 12
	ActionJOIN        = 13
)

var EnumNamesAction = map[int]string{
	ActionACK:         "ACK",
	ActionGET:         "GET",
	ActionRESPONSE:    "RESPONSE",
	ActionSET:         "SET",
	ActionNEW:         "NEW",
	ActionAPPEND:      "APPEND",
	ActionREPLACE:     "REPLACE",
	ActionUPDATE:      "UPDATE",
	ActionDELETE:      "DELETE",
	ActionCAST:        "CAST",
	ActionSUBSCRIBE:   "SUBSCRIBE",
	ActionUNSUBSCRIBE: "UNSUBSCRIBE",
	ActionCONNECT:     "CONNECT",
	ActionJOIN:        "JOIN",
}
