// automatically generated by the FlatBuffers compiler, do not modify

package indismqgo

const (
	GuaranteeNONE          = 0
	GuaranteeAT_LEAST_ONCE = 1
)

var EnumNamesGuarantee = map[int]string{
	GuaranteeNONE:          "NONE",
	GuaranteeAT_LEAST_ONCE: "AT_LEAST_ONCE",
}
